#!/bin/sh
# This script is only used for developement. It is removed by the
# distribution process.

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -tag debug -tag annot -classic-display \
                          -use-ocamlfind"}

action ()
{
    case $1 in
      default)      topkg build ;;
      apiquery)     $OCAMLBUILD apiquery.native ;;
      support)      ocaml pkg/build_support.ml ;;
      doc)          shift; topkg doc --dev $* doc/api-dev.docdir ;;
      clean)        topkg clean
                    rm -f src/tgl3.mli src/tgl3.ml src/tgl4.mli src/tgl4.ml \
                          src/tgles2.mli src/tgles2.ml src/tgles3.mli \
                          src/tgles3.ml
                    ;;
      *)            $OCAMLBUILD $* ;;
    esac
}

if [ $# -eq 0 ];
then action default ;
else action $*; fi
